In [ ]:
# using google drive on collab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# importing the neccessary libraries to collab
import pandas as pd
import numpy as np
import smtplib as sm

In [ ]:
#importing the required csv file to read it
initial=pd.read_csv('/content/drive/MyDrive/Colab resources/CsOutstandingProject/comauto_pos.csv')
initial.dropna()

,GRCODE,GRNAME,AccidentYear,DevelopmentYear,DevelopmentLag,IncurLoss_C,CumPaidLoss_C,BulkLoss_C,EarnedPremDIR_C,EarnedPremCeded_C,EarnedPremNet_C,Single,PostedReserve97_C
0,266,Public Underwriters Grp,1988,1988,1,0,0,0,0,0,0,0,932
1,266,Public Underwriters Grp,1988,1989,2,0,0,0,0,0,0,0,932
2,266,Public Underwriters Grp,1988,1990,3,0,0,0,0,0,0,0,932
3,266,Public Underwriters Grp,1988,1991,4,0,0,0,0,0,0,0,932
4,266,Public Underwriters Grp,1988,1992,5,0,0,0,0,0,0,0,932
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15795,44598,College Liability Ins Co Ltd RRG,1997,2002,6,40,40,0,159,0,159,1,248
15796,44598,College Liability Ins Co Ltd RRG,1997,2003,7,40,40,0,159,0,159,1,248
15797,44598,College Liability Ins Co Ltd RRG,1997,2004,8,40,40,0,159,0,159,1,248
15798,44598,College Liability Ins Co Ltd RRG,1997,2005,9,29,29,0,159,0,159,1,248
15799,44598,College Liability Ins Co Ltd RRG,1997,2006,10,29,29,0,159,0,159,1,248

In [ ]:
initial.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15800 entries, 0 to 15799
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GRCODE             15800 non-null  int64
 1   GRNAME             15800 non-null  object
 2   AccidentYear       15800 non-null  int64
 3   DevelopmentYear    15800 non-null  int64
 4   DevelopmentLag     15800 non-null  int64
 5   IncurLoss_C        15800 non-null  int64
 6   CumPaidLoss_C      15800 non-null  int64
 7   BulkLoss_C         15800 non-null  int64
 8   EarnedPremDIR_C    15800 non-null  int64
 9   EarnedPremCeded_C  15800 non-null  int64
 10  EarnedPremNet_C    15800 non-null  int64
 11  Single             15800 non-null  int64
 12  PostedReserve97_C  15800 non-null  int64
dtypes: int64(12), object(1)
memory usage: 1.6+ MB

In [ ]:
initial.shape

(15800, 13)

In [ ]:
Accident_yr=initial.columns[0]
Reported_yr=initial.columns[1]
Reported_claims=initial.columns[2]
Paid_Claims=initial.columns[3]
Case_outstanding=initial.columns[4]

In [ ]:
# taking hold of the required columns
initial.dropna(axis=1,inplace=True)

In [ ]:
#creating a development traingle
# A general function that can be used for developing any triangle in actuarial science but impt to remember that the data is arrranged in the ascending order in a sorted manner


def d_triangle(df,accident_yr,reported_yr,parameter):
  columns=[]
  #Setting the names of Columns
  for i in range(1,df[accident_yr].nunique()+1):
    columns.append(12*i)
  k=0                                                                           #This is counter that will ensure the shape of the triangle
  final_list=[]                                                                 #This is the final list of rows in the data frame
  unique=df[accident_yr].nunique()
  for i in range(0,df[accident_yr].nunique()):
    lis=[]
    for j in range(k,k+unique):
      lis.append(df.loc[j].at[parameter])
      k=k+1
    unique=unique-1
    if(len(lis))!=df[accident_yr].nunique():
      g=df[accident_yr].nunique()-len(lis)
      for i in range(0,g):
        lis.append(np.NaN)
    final_list.append(lis)
  bf=pd.DataFrame(final_list,columns=columns)
  bf["Accident Year"]=df[accident_yr].unique()
  first_column = bf.pop('Accident Year')
  bf.insert(0,"Accident Year",first_column)
  return bf

In [ ]:
# applying the triangle to see the development of reported claims across timeline
#repo_triangle is a dataframe containing reported claims alone

accident_yr=Accident_yr
reported_yr=Reported_yr
parameter=Reported_claims

repo_triangle=pd.DataFrame()
repo_triangle=d_triangle(initial,accident_yr,reported_yr,parameter)
repo_triangle

,Accident Year,12,24,36,48,60,72,84,96,108,...,1788,1800,1812,1824,1836,1848,1860,1872,1884,1896
0,266,1988,1988.0,1988.0,1988.0,1988.0,1988.0,1988.0,1988.0,1988.0,...,1992.0,1992.0,1993.0,1993.0,1993.0,1993.0,1993.0,1993.0,1993.0,1993.0
1,337,1993,1993.0,1994.0,1994.0,1994.0,1994.0,1994.0,1994.0,1994.0,...,1988.0,1988.0,1988.0,1988.0,1989.0,1989.0,1989.0,1989.0,1989.0,NaN
2,353,1989,1989.0,1989.0,1989.0,1989.0,1990.0,1990.0,1990.0,1990.0,...,1994.0,1994.0,1994.0,1994.0,1994.0,1994.0,1994.0,1995.0,NaN,NaN
3,388,1995,1995.0,1995.0,1995.0,1995.0,1995.0,1995.0,1995.0,1995.0,...,1989.0,1990.0,1990.0,1990.0,1990.0,1990.0,1990.0,NaN,NaN,NaN
4,460,1990,1990.0,1990.0,1990.0,1991.0,1991.0,1991.0,1991.0,1991.0,...,1995.0,1995.0,1995.0,1995.0,1995.0,1995.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,43494,1992,1992.0,1992.0,1992.0,1993.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,44091,1993,1993.0,1993.0,1993.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,44130,1993,1993.0,1993.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,44415,1993,1993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,44598,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# creating paid_triangle that will contain the paid claims development triangle


accident_yr=Accident_yr
reported_yr=Reported_yr
parameter=Paid_Claims
paid_triangle=pd.DataFrame()
paid_triangle=d_triangle(initial,accident_yr,reported_yr,parameter)
paid_triangle

,Accident Year,12,24,36,48,60,72,84,96,108,...,1788,1800,1812,1824,1836,1848,1860,1872,1884,1896
0,266,1988,1989.0,1990.0,1991.0,1992.0,1993.0,1994.0,1995.0,1996.0,...,2000.0,2001.0,1993.0,1994.0,1995.0,1996.0,1997.0,1998.0,1999.0,2000.0
1,337,2001,2002.0,1994.0,1995.0,1996.0,1997.0,1998.0,1999.0,2000.0,...,1994.0,1995.0,1996.0,1997.0,1989.0,1990.0,1991.0,1992.0,1993.0,NaN
2,353,1994,1995.0,1996.0,1997.0,1998.0,1990.0,1991.0,1992.0,1993.0,...,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,1995.0,NaN,NaN
3,388,1996,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,...,1998.0,1990.0,1991.0,1992.0,1993.0,1994.0,1995.0,NaN,NaN,NaN
4,460,1996,1997.0,1998.0,1999.0,1991.0,1992.0,1993.0,1994.0,1995.0,...,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,43494,1998,1999.0,2000.0,2001.0,1993.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,44091,1994,1995.0,1996.0,1997.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,44130,1998,1999.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,44415,2001,2002.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,44598,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# developing incremental triangle:
def incremental_triangles(cf):

  final=[]
  for i in range(0,len(cf)):
    val=[]
    for j in range(0,len(cf.columns)):
      if j==0 or j==1:
        g=cf.loc[i,cf.columns[j]]
      else:
        if cf.loc[i,cf.columns[j]]!=np.NaN:
          g=cf.loc[i,cf.columns[j]]-cf.loc[i,cf.columns[j-1]]
        else:
          g=np.NaN
      val.append(g)
    final.append(val)
  inc=pd.DataFrame(final,columns=cf.columns)
  return inc

In [ ]:
paid_incremental_triangle=incremental_triangles(paid_triangle)
paid_incremental_triangle

,Accident Year,12,24,36,48,60,72,84,96,108,...,1788,1800,1812,1824,1836,1848,1860,1872,1884,1896
0,266,1988,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,-8.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,337,2001,1.0,-8.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,-8.0,1.0,1.0,1.0,1.0,NaN
2,353,1994,1.0,1.0,1.0,1.0,-8.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-8.0,NaN,NaN
3,388,1996,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,-8.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
4,460,1996,1.0,1.0,1.0,-8.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,43494,1998,1.0,1.0,1.0,-8.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,44091,1994,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,44130,1998,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,44415,2001,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,44598,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# creating cf that will contain the Case Outstanding development triangle

accident_yr=Accident_yr
reported_yr=Reported_yr
parameter=Case_outstanding
case_out_triangle=pd.DataFrame()
case_out_triangle=d_triangle(initial,accident_yr,reported_yr,parameter)
case_out_triangle

,Accident Year,12,24,36,48,60,72,84,96,108,...,1788,1800,1812,1824,1836,1848,1860,1872,1884,1896
0,266,1,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,9.0,10.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0
1,337,9,10.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,...,7.0,8.0,9.0,10.0,1.0,2.0,3.0,4.0,5.0,NaN
2,353,6,7.0,8.0,9.0,10.0,1.0,2.0,3.0,4.0,...,4.0,5.0,6.0,7.0,8.0,9.0,10.0,1.0,NaN,NaN
3,388,2,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,...,10.0,1.0,2.0,3.0,4.0,5.0,6.0,NaN,NaN,NaN
4,460,7,8.0,9.0,10.0,1.0,2.0,3.0,4.0,5.0,...,5.0,6.0,7.0,8.0,9.0,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,43494,7,8.0,9.0,10.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,44091,2,3.0,4.0,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,44130,6,7.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,44415,9,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,44598,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#function to calculte paid_tr-on-case ratios
def paid_tr_on_case_ratio(paid_tr,case_out_tr):
  final=[]
  li=list(paid_tr.columns[1:])


  bi=list(paid_tr.columns[2:])
  for i in range(0,len(paid_tr)-1):
    val=[]
    for j in range(0,len(li)-1):
      if paid_tr.loc[i].at[li[j+1]]!=np.NaN and paid_tr.loc[i].at[li[j]]!=np.NaN:
         g=paid_tr.loc[i].at[li[j+1]]-paid_tr.loc[i].at[li[j]]
      else:
        g=np.NaN
      if case_out_tr.loc[i].at[li[j]]!=np.NaN:
        f=case_out_tr.loc[i].at[li[j]]
      else:
        f=np.NaN
      if f!=np.NaN and g!=np.NaN:
        val.append(g/f)
      else:
        val.append(np.NaN)
    final.append(val)
  nf=pd.DataFrame(final,columns=bi)

  return nf

In [ ]:
paid_ratio_triangle=pd.DataFrame()
paid_ratio_triangle=paid_tr_on_case_ratio(paid_triangle,case_out_triangle)
paid_ratio_triangle

,24,36,48,60,72,84,96,108,120,132,...,1788,1800,1812,1824,1836,1848,1860,1872,1884,1896
0,1.000000,0.500000,0.333333,0.250000,0.200000,0.166667,0.142857,0.125000,0.111111,-0.800000,...,0.125000,0.111111,-0.800000,1.000000,0.500000,0.333333,0.250000,0.200000,0.166667,0.142857
1,0.111111,-0.800000,1.000000,0.500000,0.333333,0.250000,0.200000,0.166667,0.142857,0.125000,...,0.166667,0.142857,0.125000,0.111111,-0.800000,1.000000,0.500000,0.333333,0.250000,NaN
2,0.166667,0.142857,0.125000,0.111111,-0.800000,1.000000,0.500000,0.333333,0.250000,0.200000,...,0.333333,0.250000,0.200000,0.166667,0.142857,0.125000,0.111111,-0.800000,NaN,NaN
3,0.500000,0.333333,0.250000,0.200000,0.166667,0.142857,0.125000,0.111111,-0.800000,1.000000,...,0.111111,-0.800000,1.000000,0.500000,0.333333,0.250000,0.200000,NaN,NaN,NaN
4,0.142857,0.125000,0.111111,-0.800000,1.000000,0.500000,0.333333,0.250000,0.200000,0.166667,...,0.250000,0.200000,0.166667,0.142857,0.125000,0.111111,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,1.000000,0.500000,0.333333,0.250000,0.200000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,0.142857,0.125000,0.111111,-0.800000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,0.500000,0.333333,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,0.166667,0.142857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,0.111111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#function to calculate Remaining-in-case ratios
def rem_in_case_ratio(case_out_tr):
  li=list(case_out_tr.columns[1:])
  bi=li[1:]
  final=[]
  for i in range(0,len(case_out_tr)-1):
    val=[]
    for j in range(0,len(li)-1):
      if case_out_tr.loc[i].at[li[j]]!=np.NaN and case_out_tr.loc[i].at[li[j+1]]!=np.NaN:
        c=case_out_tr.loc[i].at[li[j+1]]/case_out_tr.loc[i].at[li[j]]
        val.append(c)
      else:
        val.append(np.NaN)
    final.append(val)
  nf=pd.DataFrame(final,columns=bi)
  return nf

In [ ]:
case_ratio_triangle=pd.DataFrame()
case_ratio_triangle=rem_in_case_ratio(case_out_triangle)
case_ratio_triangle

,24,36,48,60,72,84,96,108,120,132,...,1788,1800,1812,1824,1836,1848,1860,1872,1884,1896
0,2.000000,1.500000,1.333333,1.250000,1.200000,1.166667,1.142857,1.125000,1.111111,0.100000,...,1.125000,1.111111,0.100000,2.000000,1.500000,1.333333,1.250000,1.200000,1.166667,1.142857
1,1.111111,0.100000,2.000000,1.500000,1.333333,1.250000,1.200000,1.166667,1.142857,1.125000,...,1.166667,1.142857,1.125000,1.111111,0.100000,2.000000,1.500000,1.333333,1.250000,NaN
2,1.166667,1.142857,1.125000,1.111111,0.100000,2.000000,1.500000,1.333333,1.250000,1.200000,...,1.333333,1.250000,1.200000,1.166667,1.142857,1.125000,1.111111,0.100000,NaN,NaN
3,1.500000,1.333333,1.250000,1.200000,1.166667,1.142857,1.125000,1.111111,0.100000,2.000000,...,1.111111,0.100000,2.000000,1.500000,1.333333,1.250000,1.200000,NaN,NaN,NaN
4,1.142857,1.125000,1.111111,0.100000,2.000000,1.500000,1.333333,1.250000,1.200000,1.166667,...,1.250000,1.200000,1.166667,1.142857,1.125000,1.111111,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,2.000000,1.500000,1.333333,1.250000,1.200000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,1.142857,1.125000,1.111111,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,1.500000,1.333333,1.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,1.166667,1.142857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,1.111111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def calc_measures(pf):
  columns=list(pf.columns)
  final=[]

  for i in columns:
    val=[]
    mean=pf[i].mean()
    median=pf[i].median()
    val.append(mean)
    val.append(median)
    final.append(val)
  bf=pd.DataFrame(final)
  bf.columns=["Mean","Median"]
  bf["Months"]=(bf.index+2)*12
  bf.transpose()
  return bf

In [ ]:
measures_case_out=calc_measures(case_ratio_triangle)
measures_case_out

         Mean    Median  Months
0    1.392882  1.166667      24
1    1.152381  1.142857      36
2    1.276971  1.166667      48
3    0.986884  1.142857      60
4    1.138126  1.200000      72
..        ...       ...     ...
152  1.363889  1.250000    1848
153  1.265278  1.225000    1860
154  0.877778  1.200000    1872
155  1.208333  1.208333    1884
156  1.142857  1.142857    1896

[157 rows x 3 columns]

In [ ]:
measures_paid_tr=calc_measures(paid_ratio_triangle)
measures_paid_tr

         Mean    Median  Months
0    0.392882  0.166667      24
1    0.161996  0.142857      36
2    0.276971  0.166667      48
3   -0.011817  0.142857      60
4    0.145316  0.200000      72
..        ...       ...     ...
152  0.363889  0.250000    1848
153  0.265278  0.225000    1860
154 -0.088889  0.200000    1872
155  0.208333  0.208333    1884
156  0.142857  0.142857    1896

[157 rows x 3 columns]

In [ ]:
#Fill_the_triangles
def fill_triangles_case_outstanding(df,measure,method):
  dup=df
  columns=list(dup.columns)
  for i in range(1,len(dup)):
    for j in range(1,len(columns)):
      if dup.isnull().iloc[i,j]:
        dup.loc[i,columns[j]]=round(measure[method][j-2]*dup.loc[i].at[columns[j-1]],3)
  return dup
nf=case_out=fill_triangles_case_outstanding(case_out_triangle,measures_case_out,"Mean")

In [ ]:
nf

,Accident Year,12,24,36,48,60,72,84,96,108,...,1788,1800,1812,1824,1836,1848,1860,1872,1884,1896
0,266,1,2.000,3.000,4.000,5.000,6.000,7.000,8.000,9.000,...,9.000000e+00,1.000000e+01,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00,6.000000e+00,7.000000e+00,8.000000e+00
1,337,9,10.000,1.000,2.000,3.000,4.000,5.000,6.000,7.000,...,7.000000e+00,8.000000e+00,9.000000e+00,1.000000e+01,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00,5.714000e+00
2,353,6,7.000,8.000,9.000,10.000,1.000,2.000,3.000,4.000,...,4.000000e+00,5.000000e+00,6.000000e+00,7.000000e+00,8.000000e+00,9.000000e+00,1.000000e+01,1.000000e+00,1.208000e+00,1.381000e+00
3,388,2,3.000,4.000,5.000,6.000,7.000,8.000,9.000,10.000,...,1.000000e+01,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00,6.000000e+00,5.267000e+00,6.364000e+00,7.273000e+00
4,460,7,8.000,9.000,10.000,1.000,2.000,3.000,4.000,5.000,...,5.000000e+00,6.000000e+00,7.000000e+00,8.000000e+00,9.000000e+00,1.000000e+01,1.265300e+01,1.110700e+01,1.342100e+01,1.533800e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,43494,7,8.000,9.000,10.000,1.000,1.138,1.596,1.842,2.360,...,4.025930e+10,4.412902e+10,4.537015e+10,6.592046e+10,7.362426e+10,1.004153e+11,1.270533e+11,1.115245e+11,1.347588e+11,1.540101e+11
154,44091,2,3.000,4.000,5.000,4.934,5.616,7.876,9.088,11.646,...,1.986590e+11,2.177540e+11,2.238784e+11,3.252836e+11,3.632979e+11,4.954980e+11,6.269426e+11,5.503163e+11,6.649655e+11,7.599605e+11
155,44130,6,7.000,8.000,10.216,10.082,11.475,16.093,18.570,23.797,...,4.059555e+11,4.449759e+11,4.574908e+11,6.647103e+11,7.423918e+11,1.012540e+12,1.281144e+12,1.124560e+12,1.358843e+12,1.552964e+12
156,44415,9,10.000,11.524,14.716,14.523,16.529,23.181,26.749,34.278,...,5.847526e+11,6.409590e+11,6.589859e+11,9.574722e+11,1.069367e+12,1.458498e+12,1.845405e+12,1.619856e+12,1.957326e+12,2.236944e+12
157,44598,1,1.393,1.605,2.050,2.023,2.302,3.228,3.725,4.774,...,8.143746e+10,8.926522e+10,9.177581e+10,1.333455e+11,1.489289e+11,2.031225e+11,2.570063e+11,2.255944e+11,2.725933e+11,3.115352e+11

In [ ]:
#paid_tringle_development:
def fill_triangles_paid_triangle(case_out,paid_tr,measure,method):
  columns=list(case_out.columns)
  for i in range(1,len(case_out)):
    for j in range(1,len(columns)):
      if paid_tr.isnull().iloc[i,j]:
        paid_tr.loc[i,columns[j]]=round(measure[method][j-2]*case_out.loc[i].at[columns[j-1]])
  return paid_tr

In [ ]:
nf=fill_triangles_paid_triangle(case_out_triangle,paid_incremental_triangle,measures_paid_tr,"Mean")
nf

,Accident Year,12,24,36,48,60,72,84,96,108,...,1788,1800,1812,1824,1836,1848,1860,1872,1884,1896
0,266,1988,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.000000e+00,1.000000e+00,-8.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
1,337,2001,1.0,-8.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
2,353,1994,1.0,1.0,1.0,1.0,-8.0,1.0,1.0,1.0,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.000000e+00,0.000000e+00,0.000000e+00
3,388,1996,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.000000e+00,-8.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+00,1.000000e+00,1.000000e+00
4,460,1996,1.0,1.0,1.0,-8.0,1.0,1.0,1.0,1.0,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,-1.000000e+00,2.000000e+00,2.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,43494,1998,1.0,1.0,1.0,-8.0,0.0,0.0,0.0,1.0,...,9.157695e+09,4.317046e+09,2.344354e+09,2.055031e+10,8.802474e+09,2.679105e+10,2.663795e+10,-1.129362e+10,2.323428e+10,1.925126e+10
154,44091,1994,1.0,1.0,1.0,0.0,1.0,2.0,1.0,3.0,...,4.518852e+10,2.130241e+10,1.156818e+10,1.014052e+11,4.343569e+10,1.322001e+11,1.314446e+11,-5.572823e+10,1.146492e+11,9.499507e+10
155,44130,1998,1.0,1.0,2.0,0.0,1.0,5.0,3.0,5.0,...,9.234181e+10,4.353103e+10,2.363934e+10,2.072195e+11,8.875993e+10,2.701481e+11,2.686043e+11,-1.138795e+11,2.342833e+11,1.941205e+11
156,44415,2001,1.0,2.0,3.0,0.0,2.0,7.0,4.0,8.0,...,1.330124e+11,6.270363e+10,3.405094e+10,2.984863e+11,1.278529e+11,3.891309e+11,3.869071e+11,-1.640360e+11,3.374699e+11,2.796179e+11
157,44598,1994,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.852440e+10,8.732624e+09,4.742215e+09,4.156965e+10,1.780585e+10,5.419357e+10,5.388387e+10,-2.284501e+10,4.699884e+10,3.894190e+10